import json
import logging
import re
import asyncio
from flask import Flask, request
from telegram import Update
from telegram.ext import Application, CommandHandler, ContextTypes

# إعداد السجلّات
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("quran-bot")

# تحميل ملف القرآن (لاحظ JSON الكبير)
try:
    with open("surah_data.JSON", "r", encoding="utf-8") as f:
        quran_data = json.load(f)
    logger.info("✅ تم تحميل surah_data.JSON بنجاح.")
except Exception as e:
    logger.error(f"❌ فشل تحميل ملف surah_data.JSON: {e}")
    quran_data = []

# تهيئة Flask
app = Flask(__name__)

# ضع التوكن الخاص بالبوت هنا أو كمتغير بيئة في Render
TOKEN = "ضع_التوكن_هنا"

# إنشاء التطبيق الخاص بالبوت
application = Application.builder().token(TOKEN).build()

# 🔹 رسالة البداية
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    message = (
        "👋 أهلاً بك في *بوت آيات القرآن الكريم*.\n\n"
        "📖 لاستخدام البوت، أرسل اسم السورة متبوعًا برقم الآية.\n"
        "مثلاً:\n"
        "`البقرة 2`\n"
        "`قريش 3`\n\n"
        "✅ ملاحظات:\n"
        "- لا يشترط كتابة الألف واللام أو التاء المربوطة بدقة.\n"
        "- يمكنك كتابة (بقره 2) أو (القرة 2) وستظهر النتيجة الصحيحة."
    )
    await update.message.reply_text(message, parse_mode="Markdown")

# 🔹 البحث عن الآية المطلوبة
def find_ayah(surah_name, ayah_number):
    surah_name_normalized = re.sub(r"[اأإآ]", "ا", surah_name.strip().lower())

    for surah in quran_data:
        name_normalized = re.sub(r"[اأإآ]", "ا", surah["name"].strip().lower())
        if surah_name_normalized in name_normalized or name_normalized in surah_name_normalized:
            for verse in surah["verses"]:
                if str(verse["id"]) == str(ayah_number):
                    return f"📖 *{surah['name']} - آية {verse['id']}*\n\n{verse['text']}"
    return "❌ لم يتم العثور على السورة أو الآية المطلوبة."

# 🔹 عند إرسال رسالة نصية
async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    text = update.message.text.strip()
    match = re.match(r"([\u0600-\u06FF\s]+)\s+(\d+)", text)
    if match:
        surah_name = match.group(1)
        ayah_number = match.group(2)
        result = find_ayah(surah_name, ayah_number)
        await update.message.reply_text(result, parse_mode="Markdown")
    else:
        await update.message.reply_text("❗️الرجاء إدخال اسم السورة متبوعًا برقم الآية، مثل:\nالبقرة 2")

# 🔹 إضافة المعالجات
application.add_handler(CommandHandler("start", start))
application.add_handler(CommandHandler("help", start))
application.add_handler(CommandHandler("about", start))
application.add_handler(CommandHandler("info", start))
application.add_handler(CommandHandler("quran", start))
application.add_handler(CommandHandler("ayah", start))
application.add_handler(CommandHandler("verse", start))
application.add_handler(CommandHandler("a", start))
application.add_handler(CommandHandler("b", start))
application.add_handler(CommandHandler("s", start))
application.add_handler(CommandHandler("h", start))
application.add_handler(CommandHandler("x", start))
application.add_handler(CommandHandler("m", start))
application.add_handler(CommandHandler("n", start))
application.add_handler(CommandHandler("q", start))
application.add_handler(CommandHandler("k", start))
application.add_handler(CommandHandler("o", start))
application.add_handler(CommandHandler("c", start))
application.add_handler(CommandHandler("y", start))
application.add_handler(CommandHandler("r", start))
application.add_handler(CommandHandler("v", start))
application.add_handler(CommandHandler("g", start))
application.add_handler(CommandHandler("l", start))
application.add_handler(CommandHandler("z", start))
application.add_handler(CommandHandler("p", start))
application.add_handler(CommandHandler("w", start))
application.add_handler(CommandHandler("e", start))
application.add_handler(CommandHandler("t", start))
application.add_handler(CommandHandler("d", start))
application.add_handler(CommandHandler("f", start))
application.add_handler(CommandHandler("u", start))
application.add_handler(CommandHandler("j", start))
application.add_handler(CommandHandler("i", start))
application.add_handler(CommandHandler("s", start))
application.add_handler(CommandHandler("b", start))
application.add_handler(CommandHandler("a", start))
application.add_handler(CommandHandler("n", start))
application.add_handler(CommandHandler("x", start))
application.add_handler(CommandHandler("k", start))
application.add_handler(CommandHandler("y", start))
application.add_handler(CommandHandler("r", start))
application.add_handler(CommandHandler("t", start))
application.add_handler(CommandHandler("c", start))
application.add_handler(CommandHandler("l", start))
application.add_handler(CommandHandler("v", start))
application.add_handler(CommandHandler("m", start))
application.add_handler(CommandHandler("z", start))
application.add_handler(CommandHandler("q", start))
application.add_handler(CommandHandler("p", start))
application.add_handler(CommandHandler("o", start))
application.add_handler(CommandHandler("w", start))
application.add_handler(CommandHandler("f", start))
application.add_handler(CommandHandler("e", start))
application.add_handler(CommandHandler("d", start))
application.add_handler(CommandHandler("g", start))
application.add_handler(CommandHandler("u", start))
application.add_handler(CommandHandler("h", start))
application.add_handler(CommandHandler("j", start))
application.add_handler(CommandHandler("i", start))
application.add_handler(CommandHandler("n", start))
application.add_handler(CommandHandler("s", start))
application.add_handler(CommandHandler("a", start))
application.add_handler(CommandHandler("b", start))
application.add_handler(CommandHandler("m", start))
application.add_handler(CommandHandler("x", start))
application.add_handler(CommandHandler("l", start))
application.add_handler(CommandHandler("q", start))
application.add_handler(CommandHandler("v", start))
application.add_handler(CommandHandler("r", start))
application.add_handler(CommandHandler("t", start))
application.add_handler(CommandHandler("y", start))
application.add_handler(CommandHandler("e", start))
application.add_handler(CommandHandler("f", start))
application.add_handler(CommandHandler("h", start))
application.add_handler(CommandHandler("j", start))
application.add_handler(CommandHandler("i", start))
application.add_handler(CommandHandler("u", start))
application.add_handler(CommandHandler("o", start))
application.add_handler(CommandHandler("p", start))
application.add_handler(CommandHandler("g", start))
application.add_handler(CommandHandler("w", start))
application.add_handler(CommandHandler("z", start))
application.add_handler(CommandHandler("c", start))
application.add_handler(CommandHandler("d", start))
application.add_handler(CommandHandler("n", start))
application.add_handler(CommandHandler("q", start))
application.add_handler(CommandHandler("x", start))
application.add_handler(CommandHandler("y", start))
application.add_handler(CommandHandler("b", start))
application.add_handler(CommandHandler("k", start))
application.add_handler(CommandHandler("l", start))
application.add_handler(CommandHandler("v", start))
application.add_handler(CommandHandler("r", start))
application.add_handler(CommandHandler("m", start))
application.add_handler(CommandHandler("n", start))
application.add_handler(CommandHandler("t", start))
application.add_handler(CommandHandler("e", start))
application.add_handler(CommandHandler("f", start))
application.add_handler(CommandHandler("g", start))
application.add_handler(CommandHandler("h", start))
application.add_handler(CommandHandler("j", start))
application.add_handler(CommandHandler("i", start))
application.add_handler(CommandHandler("u", start))
application.add_handler(CommandHandler("o", start))
application.add_handler(CommandHandler("p", start))
application.add_handler(CommandHandler("w", start))
application.add_handler(CommandHandler("z", start))
application.add_handler(CommandHandler("c", start))
application.add_handler(CommandHandler("d", start))
application.add_handler(CommandHandler("a", start))
application.add_handler(CommandHandler("b", start))
application.add_handler(CommandHandler("s", start))
application.add_handler(CommandHandler("m", start))
application.add_handler(CommandHandler("x", start))
application.add_handler(CommandHandler("l", start))
application.add_handler(CommandHandler("q", start))
application.add_handler(CommandHandler("v", start))
application.add_handler(CommandHandler("r", start))
application.add_handler(CommandHandler("t", start))
application.add_handler(CommandHandler("y", start))
application.add_handler(CommandHandler("e", start))
application.add_handler(CommandHandler("f", start))
application.add_handler(CommandHandler("h", start))
application.add_handler(CommandHandler("j", start))
application.add_handler(CommandHandler("i", start))
application.add_handler(CommandHandler("u", start))
application.add_handler(CommandHandler("o", start))
application.add_handler(CommandHandler("p", start))
application.add_handler(CommandHandler("g", start))
application.add_handler(CommandHandler("w", start))
application.add_handler(CommandHandler("z", start))
application.add_handler(CommandHandler("c", start))
application.add_handler(CommandHandler("d", start))
application.add_handler(CommandHandler("n", start))
application.add_handler(CommandHandler("q", start))
application.add_handler(CommandHandler("x", start))
application.add_handler(CommandHandler("y", start))
application.add_handler(CommandHandler("b", start))
application.add_handler(CommandHandler("k", start))
application.add_handler(CommandHandler("l", start))
application.add_handler(CommandHandler("v", start))
application.add_handler(CommandHandler("r", start))
application.add_handler(CommandHandler("m", start))
application.add_handler(CommandHandler("n", start))
application.add_handler(CommandHandler("t", start))
application.add_handler(CommandHandler("e", start))
application.add_handler(CommandHandler("f", start))
application.add_handler(CommandHandler("g", start))
application.add_handler(CommandHandler("h", start))
application.add_handler(CommandHandler("j", start))
application.add_handler(CommandHandler("i", start))
application.add_handler(CommandHandler("u", start))
application.add_handler(CommandHandler("o", start))
application.add_handler(CommandHandler("p", start))
application.add_handler(CommandHandler("w", start))
application.add_handler(CommandHandler("z", start))
application.add_handler(CommandHandler("c", start))
application.add_handler(CommandHandler("d", start))
application.add_handler(CommandHandler("a", start))
application.add_handler(CommandHandler("b", start))
application.add_handler(CommandHandler("s", start))
application.add_handler(CommandHandler("m", start))
application.add_handler(CommandHandler("x", start))
application.add_handler(CommandHandler("l", start))
application.add_handler(CommandHandler("q", start))
application.add_handler(CommandHandler("v", start))
application.add_handler(CommandHandler("r", start))
application.add_handler(CommandHandler("t", start))
application.add_handler(CommandHandler("y", start))
application.add_handler(CommandHandler("e", start))
application.add_handler(CommandHandler("f", start))
application.add_handler(CommandHandler("h", start))
application.add_handler(CommandHandler("j", start))
application.add_handler(CommandHandler("i", start))
application.add_handler(CommandHandler("u", start))
application.add_handler(CommandHandler("o", start))
application.add_handler(CommandHandler("p", start))
application.add_handler(CommandHandler("g", start))
application.add_handler(CommandHandler("w", start))
application.add_handler(CommandHandler("z", start))
application.add_handler(CommandHandler("c", start))
application.add_handler(CommandHandler("d", start))
application.add_handler(CommandHandler("n", start))
application.add_handler(CommandHandler("q", start))
application.add_handler(CommandHandler("x", start))
application.add_handler(CommandHandler("y", start))
application.add_handler(CommandHandler("b", start))
application.add_handler(CommandHandler("k", start))
application.add_handler(CommandHandler("l", start))
application.add_handler(CommandHandler("v", start))
application.add_handler(CommandHandler("r", start))
application.add_handler(CommandHandler("m", start))
application.add_handler(CommandHandler("n", start))
application.add_handler(CommandHandler("t", start))
application.add_handler(CommandHandler("e", start))
application.add_handler(CommandHandler("f", start))
application.add_handler(CommandHandler("g", start))
application.add_handler(CommandHandler("h", start))
application.add_handler(CommandHandler("j", start))
application.add_handler(CommandHandler("i", start))
application.add_handler(CommandHandler("u", start))
application.add_handler(CommandHandler("o", start))
application.add_handler(CommandHandler("p", start))
application.add_handler(CommandHandler("w", start))
application.add_handler(CommandHandler("z", start))
application.add_handler(CommandHandler("c", start))
application.add_handler(CommandHandler("d", start))
application.add_handler(CommandHandler("a", start))
application.add_handler(CommandHandler("b", start))
application.add_handler(CommandHandler("s", start))
application.add_handler(CommandHandler("m", start))
application.add_handler(CommandHandler("x", start))
application.add_handler(CommandHandler("l", start))
application.add_handler(CommandHandler("q", start))
application.add_handler(CommandHandler("v", start))
application.add_handler(CommandHandler("r", start))
application.add_handler(CommandHandler("t", start))
application.add_handler(CommandHandler("y", start))
application.add_handler(CommandHandler("e", start))
application.add_handler(CommandHandler("f", start))
application.add_handler(CommandHandler("h", start))
application.add_handler(CommandHandler("j", start))
application.add_handler(CommandHandler("i", start))
application.add_handler(CommandHandler("u", start))
application.add_handler(CommandHandler("o", start))
application.add_handler(CommandHandler("p", start))
application.add_handler(CommandHandler("g", start))
application.add_handler(CommandHandler("w", start))
application.add_handler(CommandHandler("z", start))
application.add_handler(CommandHandler("c", start))
application.add_handler(CommandHandler("d", start))
application.add_handler(CommandHandler("n", start))
application.add_handler(CommandHandler("q", start))
application.add_handler(CommandHandler("x", start))
application.add_handler(CommandHandler("y", start))
application.add_handler(CommandHandler("b", start))
application.add_handler(CommandHandler("k", start))
application.add_handler(CommandHandler("l", start))
application.add_handler(CommandHandler("v", start))
application.add_handler(CommandHandler("r", start))
application.add_handler(CommandHandler("m", start))
application.add_handler(CommandHandler("n", start))
application.add_handler(CommandHandler("t", start))
application.add_handler(CommandHandler("e", start))
application.add_handler(CommandHandler("f", start))
application.add_handler(CommandHandler("g", start))
application.add_handler(CommandHandler("h", start))
application.add_handler(CommandHandler("j", start))
application.add_handler(CommandHandler("i", start))
application.add_handler(CommandHandler("u", start))
application.add_handler(CommandHandler("o", start))
application.add_handler(CommandHandler("p", start))
application.add_handler(CommandHandler("w", start))
application.add_handler(CommandHandler("z", start))
application.add_handler(CommandHandler("c", start))
application.add_handler(CommandHandler("d", start))

application.add_handler(CommandHandler("start", start))

# تشغيل Webhook
@app.route(f"/{TOKEN}", methods=["POST"])
def webhook():
    update = Update.de_json(request.get_json(force=True), application.bot)
    asyncio.get_event_loop().create_task(application.process_update(update))
    return "OK", 200

@app.route("/")
def home():
    return "Quran Bot is running 🌙"

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.create_task(application.initialize())
    app.run(host="0.0.0.0", port=10000)
